# Generated by Django 5.1.3 on 2024-12-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
